export const TASK_NAME = {
  FUEL_PRICE_RESUBMIT: 'Update Fuel Pricing Configurations',
  FUEL_PRICING_ADJUST_PRICE: 'Adjust Fuel Price',
  FUEL_PRICING_MOM_TASK: 'MOM Submission',
  STAKE_HOLDER_REVIEW: 'StakeHolders Review',
  HOUSING_REQUEST_STUDY_REVIEW: 'Housing Request Study Review',
  TECHNICAL_RESEARCH_REVIEW: 'Technical Research Review',
  TECHNICAL_REPORT_SECTION_HEAD_REVIEW: 'TechRpt Section Head Review',
  SOCIAL_RESEARCH_REVIEW: 'Social Research Review',
  SOCIAL_REPORT_SECTION_HEAD_REVIEW: 'Social Report Section Head Review',
  HOUSING_STUDY_SECTION_REVIEW: 'Housing Study Section Review',
  HOUSING_EXECUTIVE_COMMITTEE_REVIEW: 'Exec Committee Review',
  QARAR_CREATION: 'Qarar Creation',
  QARAR_APPROVAL: 'Qarar Approval',
  APPLICANT_RESUBMISSION: 'Applicant Resubmission',
  APPLICANT_RESUBMISSION_STUDY_SECTION: 'Applicant Resubmission StudySection',
  APPLICANT_DIGITAL_SIGNAR_TASK: 'Digital Signer Task',
  SELLER_ESIGN_TASK: 'Seller Esign',
  AUDIT_TEAM_MAINTENANCE_EXTENSION_REVIEW: 'Maintenance Extension Review',
};

// ******* HOUSING - RELATED ******** //
export const INITIATED_BY = {
  HOUSING_REQUEST_STUDY_TEAM: 'StudyTeam',
  HOUSING_STUDY_SECTION_TEAM: 'StudySection',
  HOUSING_EXECUTIVE_COMMITTE_TEAM: 'ExecCommittee',
};
// ******* HOUSING - RELATED ******** //
export const VISIT_TYPE = {
  TECHNICAL: 'TECHNICAL',
  SOCIAL: 'SOCIAL',
};

export const TASK_ACTIONS = {
  APPROVED: 'APPROVED',
  MORE_INFO: 'MORE_INFO_REQUEST',
  REJECTED: 'REJECTED',
  SUBMITTED: 'SUBMIT',
  RESUBMIT: 'RESUBMIT',
  TECHNICAL: 'TECHNICAL',
  SOCIAL: 'SOCIAL',
  EXTEND: 'EXTEND',
};
export const TASK_BUTTONS = {
  APPROVE: 'APPROVE',
  APPROVED: 'APPROVED',
  REJECT: 'REJECT',
  REJECTED: 'REJECTED',
  CHANGE_REQ: 'CHANGE_REQ',
  NEED_MORE_INFORMATION: 'NEED_MORE_INFORMATION',
  MORE_INFO: 'MORE_INFO',
  EXTEND: 'EXTEND',
};

export const UPDATE_REQUEST_DETAILS_TASK_ACTIONS = [
  'RESUBMIT',
  'SUBMIT',
  'SUBMITTED',
  'ADD_ADJUSTMENTS',
  'APPROVED',
  'APPROVE',
  'REJECTED',
  'REJECT',
  'EXTEND',
  'EXTEND_REJECTED',
  'EXTEND_APPROVED',
  'CANCEL',
];
